- name: Install dependencies
  import_tasks: deps.yml

- name: Install and start Jenkins
  import_tasks: install.yml

- name: Configure admin user and disable setup wizard
  import_tasks: configure_admin.yml

- name: Install Jenkins plugins
  import_tasks: plugins.yml

- name: Create pipeline job
  import_tasks: pipeline_job.yml
