- name: Update system
  dnf:
    name: "*"
    state: latest

- name: Install base tools
  dnf:
    name:
      - git
      - curl
      - vim
      - python3
      - python3-pip
      - epel-release
    state: present

- name: Disable Cockpit socket
  systemd:
    name: cockpit.socket
    enabled: false
    state: stopped

- name: Disable Cockpit service
  systemd:
    name: cockpit
    enabled: false
    state: stopped
